/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.chdor.schema_registry.schemas.management.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Descriptive card of series of the year 1970- 1980 */
@org.apache.avro.specific.AvroGenerated
public class TVShow1 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 9005881455287106824L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TVShow1\",\"namespace\":\"com.chdor.schema_registry.schemas.management.avro.model\",\"doc\":\"Descriptive card of series of the year 1970- 1980\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Name of the Serie\"},{\"name\":\"date\",\"type\":\"int\",\"doc\":\"Serie release date\",\"default\":-1},{\"name\":\"characters\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Character\",\"doc\":\"A tiny Series character identity card\",\"fields\":[{\"name\":\"firstName\",\"type\":[\"null\",\"string\"],\"doc\":\"Character fisrt name\"},{\"name\":\"lastName\",\"type\":[\"null\",\"string\"],\"doc\":\"Character last name\",\"default\":null},{\"name\":\"age\",\"type\":\"int\",\"doc\":\"Character Age\"}]}},\"doc\":\"A tiny Series character (Heros) identity card\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TVShow1> ENCODER =
      new BinaryMessageEncoder<TVShow1>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TVShow1> DECODER =
      new BinaryMessageDecoder<TVShow1>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TVShow1> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TVShow1> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TVShow1> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TVShow1>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TVShow1 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TVShow1 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TVShow1 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TVShow1 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Name of the Serie */
   private java.lang.CharSequence name;
  /** Serie release date */
   private int date;
  /** A tiny Series character (Heros) identity card */
   private java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> characters;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TVShow1() {}

  /**
   * All-args constructor.
   * @param name Name of the Serie
   * @param date Serie release date
   * @param characters A tiny Series character (Heros) identity card
   */
  public TVShow1(java.lang.CharSequence name, java.lang.Integer date, java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> characters) {
    this.name = name;
    this.date = date;
    this.characters = characters;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return date;
    case 2: return characters;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: date = (java.lang.Integer)value$; break;
    case 2: characters = (java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return Name of the Serie
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * Name of the Serie
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return Serie release date
   */
  public int getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * Serie release date
   * @param value the value to set.
   */
  public void setDate(int value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'characters' field.
   * @return A tiny Series character (Heros) identity card
   */
  public java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> getCharacters() {
    return characters;
  }


  /**
   * Sets the value of the 'characters' field.
   * A tiny Series character (Heros) identity card
   * @param value the value to set.
   */
  public void setCharacters(java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> value) {
    this.characters = value;
  }

  /**
   * Creates a new TVShow1 RecordBuilder.
   * @return A new TVShow1 RecordBuilder
   */
  public static com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder newBuilder() {
    return new com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder();
  }

  /**
   * Creates a new TVShow1 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TVShow1 RecordBuilder
   */
  public static com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder newBuilder(com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder other) {
    if (other == null) {
      return new com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder();
    } else {
      return new com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder(other);
    }
  }

  /**
   * Creates a new TVShow1 RecordBuilder by copying an existing TVShow1 instance.
   * @param other The existing instance to copy.
   * @return A new TVShow1 RecordBuilder
   */
  public static com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder newBuilder(com.chdor.schema_registry.schemas.management.avro.model.TVShow1 other) {
    if (other == null) {
      return new com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder();
    } else {
      return new com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder(other);
    }
  }

  /**
   * RecordBuilder for TVShow1 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TVShow1>
    implements org.apache.avro.data.RecordBuilder<TVShow1> {

    /** Name of the Serie */
    private java.lang.CharSequence name;
    /** Serie release date */
    private int date;
    /** A tiny Series character (Heros) identity card */
    private java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> characters;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.characters)) {
        this.characters = data().deepCopy(fields()[2].schema(), other.characters);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TVShow1 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.chdor.schema_registry.schemas.management.avro.model.TVShow1 other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.date)) {
        this.date = data().deepCopy(fields()[1].schema(), other.date);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.characters)) {
        this.characters = data().deepCopy(fields()[2].schema(), other.characters);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * Name of the Serie
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * Name of the Serie
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * Name of the Serie
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * Name of the Serie
      * @return This builder.
      */
    public com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * Serie release date
      * @return The value.
      */
    public int getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * Serie release date
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder setDate(int value) {
      validate(fields()[1], value);
      this.date = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * Serie release date
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'date' field.
      * Serie release date
      * @return This builder.
      */
    public com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder clearDate() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'characters' field.
      * A tiny Series character (Heros) identity card
      * @return The value.
      */
    public java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> getCharacters() {
      return characters;
    }


    /**
      * Sets the value of the 'characters' field.
      * A tiny Series character (Heros) identity card
      * @param value The value of 'characters'.
      * @return This builder.
      */
    public com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder setCharacters(java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> value) {
      validate(fields()[2], value);
      this.characters = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'characters' field has been set.
      * A tiny Series character (Heros) identity card
      * @return True if the 'characters' field has been set, false otherwise.
      */
    public boolean hasCharacters() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'characters' field.
      * A tiny Series character (Heros) identity card
      * @return This builder.
      */
    public com.chdor.schema_registry.schemas.management.avro.model.TVShow1.Builder clearCharacters() {
      characters = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TVShow1 build() {
      try {
        TVShow1 record = new TVShow1();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.date = fieldSetFlags()[1] ? this.date : (java.lang.Integer) defaultValue(fields()[1]);
        record.characters = fieldSetFlags()[2] ? this.characters : (java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TVShow1>
    WRITER$ = (org.apache.avro.io.DatumWriter<TVShow1>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TVShow1>
    READER$ = (org.apache.avro.io.DatumReader<TVShow1>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.name);

    out.writeInt(this.date);

    long size0 = this.characters.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.chdor.schema_registry.schemas.management.avro.model.Character e0: this.characters) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);

      this.date = in.readInt();

      long size0 = in.readArrayStart();
      java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> a0 = this.characters;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.chdor.schema_registry.schemas.management.avro.model.Character>((int)size0, SCHEMA$.getField("characters").schema());
        this.characters = a0;
      } else a0.clear();
      SpecificData.Array<com.chdor.schema_registry.schemas.management.avro.model.Character> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.chdor.schema_registry.schemas.management.avro.model.Character>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.chdor.schema_registry.schemas.management.avro.model.Character e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.chdor.schema_registry.schemas.management.avro.model.Character();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.name = in.readString(this.name instanceof Utf8 ? (Utf8)this.name : null);
          break;

        case 1:
          this.date = in.readInt();
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<com.chdor.schema_registry.schemas.management.avro.model.Character> a0 = this.characters;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.chdor.schema_registry.schemas.management.avro.model.Character>((int)size0, SCHEMA$.getField("characters").schema());
            this.characters = a0;
          } else a0.clear();
          SpecificData.Array<com.chdor.schema_registry.schemas.management.avro.model.Character> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.chdor.schema_registry.schemas.management.avro.model.Character>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.chdor.schema_registry.schemas.management.avro.model.Character e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.chdor.schema_registry.schemas.management.avro.model.Character();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










